DROP TABLE IF EXISTS person;
CREATE TABLE person(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	age INT (11) NOT NULL DEFAULT -1 COMMENT 'age',
	address VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'address',
	birthday DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'birthday',
	remark VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'remark',
	money DECIMAL(13,4) NOT NULL DEFAULT -1 COMMENT 'money',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;